architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/academy-common.accesswidener")
}

dependencies {
    modCompileOnly("net.fabricmc:fabric-loader:$rootProject.fabric_loader_version")
    modCompileOnly("dev.architectury:architectury:$rootProject.architectury_api_version")

    modCompileOnly("com.cobblemon:mod:1.6.1+1.21.1")
    modCompileOnly(files("jars/molang-1.1.18.jar"))

    modCompileOnly("maven.modrinth:numismatic-overhaul:0.3.4+1.21")
    modCompileOnly(include("io.wispforest:owo-sentinel:0.12.15.4+1.21"))
    modCompileOnly(annotationProcessor("io.wispforest:owo-lib:0.12.15.4+1.21"))

    modCompileOnly("maven.modrinth:enhanced-celestials:6.0.2.4-fabric")
    modCompileOnly("maven.modrinth:corgilib:1.21.1-5.0.0.7-Fabric")
    modCompileOnly("maven.modrinth:data-anchor:2.0.0.12-fabric")

    modCompileOnly("software.bernie.geckolib:geckolib-fabric-1.21.1:4.7.5.1")

    modCompileOnly("maven.modrinth:eternal-starlight:0.5.1+1.21.1+fabric")

    modCompileOnly("maven.modrinth:itemzoomer:1.1.0-1.21.1")

    modCompileOnly("maven.modrinth:journeymap:WvOAHk8e")

    modCompileOnly("maven.modrinth:modernfix:5.24.3+mc1.21.1")

    modCompileOnly("maven.modrinth:displayed:1.0.2-fabric-1.21.1")

    modCompileOnly("maven.modrinth:cobblemon-myths-and-legends-sidemod:1.7.2")

    modCompileOnly("maven.modrinth:rad-gyms:0.2-alpha.2")

    modCompileOnly("maven.modrinth:fading-clouds:1.1.0")

    modCompileOnly("com.squareup.okhttp3:okhttp:4.12.0")

    modCompileOnly("maven.modrinth:trinkets:3.10.0")
    modCompileOnly("maven.modrinth:cardinal-components-api:6.1.2")
}