name: Build Star Academy Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Fabric Project
        run: ./gradlew :fabric:build

      - name: Filter Non-Normal JARs
        run: |
          mkdir filtered-libs
          find fabric/build/libs -type f -name '*.jar' ! -name '*-dev*' ! -name '*-sources*' -exec cp {} filtered-libs/ \;
          find forge/build/libs -type f -name '*.jar' ! -name '*-dev*' ! -name '*-sources*' -exec cp {} filtered-libs/ \;
          cd filtered-libs
          for file in *.jar; do
            mv "$file" "$(echo "$file" | sed -E 's/-(.*-.*-.*)\.jar$/.jar/')"
          done

      - name: Upload Filtered Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: final-build
          path: filtered-libs/